import { readFileSync } from "fs";
import { join } from "path";

describe("docs content", () => {
  const repoRoot = join(__dirname, "..", "..");

  it("contains user and developer markdown guides with expected sections", () => {
    const user = readFileSync(join(repoRoot, "docs", "user-guide.md"), "utf8");
    const dev = readFileSync(join(repoRoot, "docs", "developer-guide.md"), "utf8");
    const replayStorage = readFileSync(join(repoRoot, "docs", "replay-storage-strategy.md"), "utf8");
    const egressArchitecture = readFileSync(join(repoRoot, "docs", "egress-architecture.md"), "utf8");
    const telemetry = readFileSync(join(repoRoot, "docs", "telemetry-alarms.md"), "utf8");
    const nxdomain = readFileSync(join(repoRoot, "docs", "route53-nxdomain-runbook.md"), "utf8");
    const monetization = readFileSync(join(repoRoot, "docs", "player-monetization-policy.md"), "utf8");
    const botQuickstart = readFileSync(join(repoRoot, "docs", "bot-api-quickstart.md"), "utf8");
    const botBenchmark = readFileSync(join(repoRoot, "docs", "bot-benchmark-suite.md"), "utf8");
    const launchPackage = readFileSync(join(repoRoot, "docs", "bot-first-launch-package.md"), "utf8");
    const chatStrategy = readFileSync(join(repoRoot, "docs", "chat-product-strategy.md"), "utf8");
    const chatEmotionGovernance = readFileSync(join(repoRoot, "docs", "chat-emotion-governance.md"), "utf8");
    const emotionPolicy = readFileSync(join(repoRoot, "docs", "emotion-classification-policy.md"), "utf8");
    const llmSafety = readFileSync(join(repoRoot, "docs", "llm-safety-and-agent-policy.md"), "utf8");
    const economyPolicy = readFileSync(join(repoRoot, "docs", "economy-and-rewards-policy.md"), "utf8");
    const mechanicsPolicy = readFileSync(join(repoRoot, "docs", "experimental-mechanics-policy.md"), "utf8");
    const egressDecision = readFileSync(join(repoRoot, "docs", "production-egress-decision.md"), "utf8");
    const fixedEgressRunbook = readFileSync(join(repoRoot, "docs", "fixed-egress-migration-runbook.md"), "utf8");
    const fixedEgressChecklist = readFileSync(join(repoRoot, "docs", "fixed-egress-aws-checklist.md"), "utf8");
    const contentOps = readFileSync(join(repoRoot, "docs", "content-and-community-ops.md"), "utf8");
    expect(user).toContain("# Binary-2048 User Guide");
    expect(user).toContain("## Replay and Sharing");
    expect(dev).toContain("# Binary-2048 Developer Guide");
    expect(dev).toContain("## Replay Model");
    expect(replayStorage).toContain("# Binary-2048 Replay Storage Strategy");
    expect(replayStorage).toContain("## Phase 1: No-DB Default (Current Lightweight Mode)");
    expect(egressArchitecture).toContain("# Binary-2048 Egress Architecture Note");
    expect(egressArchitecture).toContain("Amplify `WEB_COMPUTE`");
    expect(egressArchitecture).toContain("no guaranteed stable outbound IP address");
    expect(telemetry).toContain("# Telemetry And Anomaly Visibility");
    expect(telemetry).toContain("GET /api/ops/telemetry");
    expect(nxdomain).toContain("# Route 53 NXDOMAIN Runbook");
    expect(nxdomain).toContain("npm run ops:waf:nxdomain");
    expect(monetization).toContain("# Player Monetization Policy");
    expect(monetization).toContain("never pay-to-win");
    expect(botQuickstart).toContain("# Bot API Quickstart");
    expect(botQuickstart).toContain("Python starter");
    expect(botBenchmark).toContain("# Bot Benchmark Suite");
    expect(launchPackage).toContain("# Bot-First Launch Package");
    expect(chatStrategy).toContain("# Binary-2048 Chat And Product Messaging Strategy");
    expect(chatStrategy).toContain("should not ship open player-to-player chat");
    expect(chatEmotionGovernance).toContain("# Binary-2048 Chat And Emotion Governance");
    expect(chatEmotionGovernance).toContain("Emotion or mood-derived behavior must be opt-in");
    expect(emotionPolicy).toContain("# Binary-2048 Emotion Classification Policy");
    expect(emotionPolicy).toContain("roberta-base-go_emotions");
    expect(llmSafety).toContain("# Binary-2048 LLM Safety And Agent Policy");
    expect(llmSafety).toContain("Untrusted text must never directly control");
    expect(economyPolicy).toContain("# Binary-2048 Economy And Rewards Policy");
    expect(economyPolicy).toContain("three-layer economy");
    expect(mechanicsPolicy).toContain("# Binary-2048 Experimental Mechanics Policy");
    expect(mechanicsPolicy).toContain("subtract tiles");
    expect(egressDecision).toContain("# Binary-2048 Production Egress Decision");
    expect(egressDecision).toContain("stay on Amplify `WEB_COMPUTE`");
    expect(fixedEgressRunbook).toContain("# Binary-2048 Fixed Egress Migration Runbook");
    expect(fixedEgressRunbook).toContain("Mongo-touching workloads move off Amplify `WEB_COMPUTE`");
    expect(fixedEgressChecklist).toContain("# Binary-2048 Fixed Egress AWS Checklist");
    expect(fixedEgressChecklist).toContain("infra/fixed-egress-vpc-template.yml");
    expect(contentOps).toContain("# Binary-2048 Content And Community Operations");
    expect(contentOps).toContain("Tile Of The Week Program");
  });

  it("links docs routes from api docs page and README", () => {
    const apiDocsPage = readFileSync(join(repoRoot, "app", "api-docs", "page.tsx"), "utf8");
    const readme = readFileSync(join(repoRoot, "README.md"), "utf8");
    expect(apiDocsPage).toContain('href="/docs"');
    expect(apiDocsPage).toContain('href="/docs/user"');
    expect(apiDocsPage).toContain('href="/docs/developer"');
    expect(readme).toContain("http://localhost:3000/docs");
    expect(readme).toContain("http://localhost:3000/docs/user");
    expect(readme).toContain("http://localhost:3000/docs/developer");
    expect(readme).toContain("http://localhost:3000/monetization");
    expect(readme).toContain("npm run ops:waf:nxdomain");
    expect(readme).toContain("NOTIFICATION_THRESHOLDS");
    expect(readme).toContain("REQUIRE_ALARM_ACTIONS=1");
    expect(apiDocsPage).toContain('href="/docs/user"');
  });
});
